# Generated by Django 3.1.7 on 2021-03-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_auto_20210302_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='hora',
            field=models.IntegerField(choices=[(1, '5PM - 6PM'), (2, '6PM - 7PM'), (3, '7PM - 8PM'), (4, '8PM - 9PM'), (5, '9PM - 10PM')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
