# Generated by Django 3.1.7 on 2021-03-02 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_auto_20210302_0059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
