# Generated by Django 3.1.7 on 2021-03-02 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turnos', '0004_delete_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.CharField(choices=[('5PM - 6PM', '5PM - 6PM'), ('6PM - 7PM', '6PM - 7PM'), ('7PM - 8PM', '7PM - 8PM'), ('8PM - 9PM', '8PM - 9PM'), ('9PM - 10PM', '9PM - 10PM')], max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
