# Generated by Django 3.1.7 on 2021-03-02 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora',
        ),
    ]
