# Generated by Django 3.1.7 on 2021-03-02 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_auto_20210302_0156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
