# Generated by Django 3.1.7 on 2021-03-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0012_remove_turno_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='persona',
        ),
        migrations.AddField(
            model_name='turno',
            name='dni',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
