# Generated by Django 3.1.7 on 2021-03-08 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turnos', '0013_auto_20210304_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='dni',
        ),
        migrations.AddField(
            model_name='turno',
            name='persona',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
            preserve_default=False,
        ),
    ]
