# Generated by Django 3.1.7 on 2021-03-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0015_auto_20210310_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
