# Generated by Django 3.1.7 on 2021-03-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0017_remove_turno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
