# Generated by Django 3.1.7 on 2021-03-12 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0018_turno_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='estado',
        ),
    ]
